# Generated by Django 4.2.6 on 2023-12-12 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Create At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update At"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.comment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("title", models.CharField(max_length=25)),
                ("description", models.CharField(max_length=255)),
                ("language", models.CharField(blank=True, max_length=25, null=True)),
                ("knowledge_level", models.IntegerField(blank=True, null=True)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Create At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update At"),
                ),
                (
                    "comments",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.comment",
                    ),
                ),
            ],
        ),
    ]
